// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PKD_FontsManager","status":true,"description":"(v.1.0.1)[BASIC] Fonts Manager - custom fonts and colors","parameters":{"fontsToLoad:strA":"[\"Fire_Emblem.ttf\"]","isGlobal:b":"true","isAutoLoad:b":"false","spacer|defaultFonts":"","defaultSetup":"","allItemsFont":"","allArmorsFont":"","allWeaponsFont":"","allSkillsFont":"","allActorNamesFont":"","allActorClassFont":"","allActorNickFont":"","allActorLevelFont":"","spacer|colors":"","pallete:strA":"[]","userPalletes:structA":"[]","isGlobalColors:b":"true","spacer|endHolder":""}}
];
